CREATE TABLE [dbo].[ImageData]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	[OriginalName] VARCHAR(200) NOT NULL,
	[ImagePath] VARCHAR(250) NOT NULL,
	[Description] VARCHAR(500) NULL
)
